
ALTER TABLE public.pet_friendly_places
  ADD COLUMN IF NOT EXISTS source_id text,
  ADD COLUMN IF NOT EXISTS name_fr text,
  ADD COLUMN IF NOT EXISTS brand text,
  ADD COLUMN IF NOT EXISTS operator text,
  ADD COLUMN IF NOT EXISTS tags text,
  ADD COLUMN IF NOT EXISTS housenumber text,
  ADD COLUMN IF NOT EXISTS street text,
  ADD COLUMN IF NOT EXISTS postcode text,
  ADD COLUMN IF NOT EXISTS state text,
  ADD COLUMN IF NOT EXISTS region text,
  ADD COLUMN IF NOT EXISTS department text,
  ADD COLUMN IF NOT EXISTS phone2 text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS facebook text,
  ADD COLUMN IF NOT EXISTS instagram text,
  ADD COLUMN IF NOT EXISTS opening_hours_covid text,
  ADD COLUMN IF NOT EXISTS price_range text,
  ADD COLUMN IF NOT EXISTS price_level text,
  ADD COLUMN IF NOT EXISTS accepts_other_pets boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS dogs_indoor_allowed boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS max_pet_weight_kg numeric,
  ADD COLUMN IF NOT EXISTS pet_fee boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS pet_fee_amount numeric,
  ADD COLUMN IF NOT EXISTS water_bowl_provided boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS pet_menu boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS pet_area boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS takeaway boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS delivery boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS wheelchair text,
  ADD COLUMN IF NOT EXISTS parking text,
  ADD COLUMN IF NOT EXISTS wifi boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS air_conditioning boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS payment_card boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS payment_contactless boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS stars text,
  ADD COLUMN IF NOT EXISTS rooms integer,
  ADD COLUMN IF NOT EXISTS checkin text,
  ADD COLUMN IF NOT EXISTS checkout text,
  ADD COLUMN IF NOT EXISTS tents boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS caravans boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS electric_hookup boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS google_place_id text,
  ADD COLUMN IF NOT EXISTS google_rating numeric,
  ADD COLUMN IF NOT EXISTS google_review_count integer,
  ADD COLUMN IF NOT EXISTS google_photo_url text,
  ADD COLUMN IF NOT EXISTS google_maps_url text,
  ADD COLUMN IF NOT EXISTS last_updated timestamp with time zone,
  ADD COLUMN IF NOT EXISTS note text;
